export const registryABI = [
  'function registerNode(bytes32 codeHash) external',
  'function unregisterNode() external',
  'function finalizeCluster(address[] members, string moneroAddress) external returns (bytes32 clusterId)',
  'function dissolveCluster(bytes32 clusterId) external returns (bool rewarded)',
  'function clusters(bytes32) external view returns (string moneroAddress, uint256 createdAt, bool finalized)',
  'function getRegisteredNodes(uint256 offset, uint256 limit) external view returns (address[] memory)',
  'function canParticipate(address node) external view returns (bool)',
  'function canDissolve(bytes32 clusterId) external view returns (bool, uint256 blacklistedCount)',
  'function isClusterActive(bytes32 clusterId) external view returns (bool)',
  'function getClusterMembers(bytes32 clusterId) external view returns (address[] memory)',
  'function getClusterHealth(bytes32 clusterId) external view returns (uint256 healthy, uint256 slashed, uint256 blacklisted)',
  'function canRejoinCluster(address node) external view returns (bool canRejoin, bytes32 clusterId)',
  'function nodes(address) external view returns (bytes32 codeHash, bool registered, bool inCluster)',
  'function nodeToCluster(address) external view returns (bytes32)',
  'function getActiveClusters() external view returns (bytes32[] memory)',
  'function getClusterStake(bytes32 clusterId) external view returns (uint256)',
  'function selectClusterForRequest(bytes32 requestKey) external view returns (bytes32)',
];
export const stakingABI = [
  'function getNodeInfo(address node) external view returns (uint256,uint256,uint256,bool,uint256,uint256,uint256)',
  'function stake(bytes32 _codeHash, string _feeHint) external',
  'function topUpStake() external',
  'function getActiveNodes() external view returns (address[] memory)',
  'function proveHeartbeat(address node, uint256 timestamp, bytes calldata sig) external',
  'function slashForDowntime(address _node) external',
  'function slashForDowntimeWithProof(address _node, uint256 lastHeartbeatTs, bytes calldata sig) external',
  'function openDowntimeChallenge(bytes32 clusterId, address node, uint8 stage, bytes32 requestId, uint256[] lastSeen, bytes[] signatures) external',
  'function cancelDowntimeChallenge() external',
  'function finalizeDowntimeSlash(address node) external',
  'function getDowntimeChallenge(address node) external view returns (bytes32,uint256,uint256,uint256,uint256)',
  'function getSlashingInfo(address _node) external view returns (uint256 slashingStage, uint256 lastProved, bool isBlacklisted)',
  'function isBlacklisted(address _node) external view returns (bool)',
  'function getDissolutionPool() external view returns (uint256)',
  'function owner() external view returns (address)',
  'function slashForFraudBatch(bytes32 clusterId, bytes32 fraudId, address[] targets, bytes[] signatures) external',
];
export const zfiABI = [
  'function balanceOf(address) view returns (uint256)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function decimals() view returns (uint8)',
];
export const exchangeCoordinatorABI = [
  'function multisigExchangeData(bytes32 clusterId, uint8 round, address node) external view returns (bytes32)',
  'function submitExchangeInfo(bytes32 clusterId, uint8 round, bytes32 exchangeDigest) external',
  'function getExchangeRoundInfo(bytes32 clusterId, uint8 round, address[] clusterNodes) external view returns (address[] addresses, bytes32[] exchangeDigests)',
  'function getExchangeRoundStatus(bytes32 clusterId, uint8 round) external view returns (bool complete, uint8 submitted)',
];
export const bridgeABI = [
  'function mint(bytes32 clusterId, bytes32 depositId, uint256 amount, bytes[] signatures) external',
  'function claimFromBatch(bytes32 merkleRoot, bytes32[] proof, bytes32 clusterId, bytes32 depositId, address recipient, uint256 amount, bytes[] signatures) external',
  'function burnForXMR(bytes32 clusterId, uint256 amount, string xmrAddress) external',
  'function burnForXMRWithReadySignatures(bytes32 clusterId, uint256 amount, string xmrAddress, uint256 readyTimestamp, bytes[] readySignatures) external',
  'function requeueWithdrawal(bytes32 burnTxHash) external',
  'function usedDepositIds(bytes32) external view returns (bool)',
  'function epochDuration() view returns (uint256)',
  'function getCurrentEpoch() view returns (uint256)',
  'function epochReservedCount(uint256) view returns (uint256)',
  'function epochLocked(bytes32 clusterId, uint256 epoch) view returns (bool)',
  'function getBribeStatus(bytes32 clusterId) view returns (uint256 currentEpoch, uint256 targetEpoch, uint256 reservedSlots, uint256 availableBribeSlots, uint256 nextSlotCost, bool windowOpen, uint256 windowClosesInSeconds, bool currentEpochLocked)',
  'function burnHeartbeatMaxAgeSec() view returns (uint256)',
  'function BURN_READY_MAX_FUTURE_SEC() view returns (uint256)',
  'event TokensMinted(address indexed user, bytes32 indexed clusterId, bytes32 indexed depositId, uint256 userAmount, uint256 fee)',
  'event TokensBurned(address indexed user, bytes32 indexed clusterId, string xmrAddress, uint256 burnAmount, uint256 fee, bool usedReservation)',
  'event WithdrawalRequeued(bytes32 indexed burnTxHash, address indexed caller)',
  'event SlotReserved(uint256 indexed targetEpoch, address indexed user, uint256 slotIndex, uint256 zfiCost)',
  'event EpochLocked(bytes32 indexed clusterId, uint256 indexed epoch, uint256 timestamp)',
];
export const configABI = [
  'function registry() external view returns (address)',
  'function staking() external view returns (address)',
  'function zfiToken() external view returns (address)',
  'function bridge() external view returns (address)',
  'function feePool() external view returns (address)',
  'function zxmrToken() external view returns (address)',
  'function getConfig() external view returns (address, address, address, address, address, address)',
];
export default {
  registryABI,
  stakingABI,
  zfiABI,
  exchangeCoordinatorABI,
  bridgeABI,
  configABI,
};
